### ISSUE TITLE
catch google api return error

### ISSUE THREAD

**Issue by talomone** [spatie/geocoder#1]
Hi,
first off thanks for the package.
I'm using it to run a batch over some db records, and I have come across a setback.

in this file, line 62:
geocoder/src/Spatie/Geocoder/Google/Geocoder.php
it would be nice to have this condition caught by a newException, since we enter this condition when google api returns a failure (for instance query limit). As it is now, it is not possible to make out whether the address could not be found or some other problem have occurred.

Also, it would come in handy to set the api key to run the query.

ps I am happy to contribute if needed

**Comment by freekmurze** [comment]
Hi,

feel free to submit a pull request to implement these changes.

**Comment by freekmurze** [comment]
Going to close this one for now. If you still need these change, feel free to submit a pr.

**Comment by talomone** [comment]
Sure,  I completely forgot about this. Sorry about that.
