### ISSUE TITLE
v3.14 Update: Undefined property $partial_match

### ISSUE THREAD

**Issue by novelnet** [spatie/geocoder#104]
Hi,

since the update today i can't geocode all of my addresses anymore:
`$coordinates = Geocoder::getCoordinatesForAddress($lead->route.' '.$lead->street_number.', '.$lead->postal_code.' '.$lead->locality);`

I get following error:
``
ErrorException: Undefined property: stdClass::$partial_match in /var/www/vhosts/leadmarkt.ch/httpdocs/vendor/spatie/geocoder/src/Geocoder.php:143
``

**Comment by freekmurze** [comment]
Thanks for reporting, this has been fixed in the latest version.

**Comment by novelnet** [comment]
Thanks a lot!
