### ISSUE TITLE
Include more parameters

### ISSUE THREAD

**Issue by michelecurletta** [spatie/geocoder#12]
Hi,
what do you think about including some required/optional parameters (https://developers.google.com/maps/documentation/geocoding/intro#geocoding) through a config file?
Some of them (like API key) are required by Google's policy and others (like language param) are very useful in order to format the response in a proper way (like the correct translation).

**Comment by freekmurze** [comment]
I’d probably accept a PR that adds some of those parameters (in a config
file). Let me know which ones your going to add (and which ones would go in
a config file).





Freek Van der Herten
Samberstraat 69 D
2060 Antwerpen
T:  +32 3 292 56 79
M: +32 495 84 27 91
https://spatie.be

**Comment by michelecurletta** [comment]
The params I'll go to add into config file are these:

1. Key

2. language 

3. region

Do you agree?

**Comment by freekmurze** [comment]
Yup, do it 😄

**Comment by freekmurze** [comment]
We'll handle this in #14
