### ISSUE TITLE
Example use of Geocoder in Laravel

### ISSUE THREAD

**Issue by PhilMarc** [spatie/geocoder#2]
So I am trying to use the geocoder package this way (Laravel 5.1)

In my AddressController.php

    use Spatie\Geocoder\Geocoder;

	public function postCreate(AddressRequest $request)
	{
		if ($request->has('address')) {
			return Geocoder::getCoordinatesForQuery($request->input('address'));
		}
	}

It throws the error `Non-static method Spatie\Geocoder\Geocoder::getCoordinatesForQuery() cannot be called statically, assuming $this from incompatible context`

So I changed it to 

			    $coordinates = new Geocoder();
			    $coordinates->getCoordinatesForQuery($request->input('address'));

And it now returns `Cannot instantiate interface Spatie\Geocoder\Geocoder`

What am I doing wrong?

**Comment by freekmurze** [comment]
You have to use the facade.

Change:
```php
use Spatie\Geocoder\Geocoder;
```
to
```php
use Geocoder;
```
