### ISSUE TITLE
i can't install it on laravel 5.3

### ISSUE THREAD

**Issue by IronStar** [spatie/geocoder#21]
hello,

Composer step works well. I added lines in config.app.php as indicated, but I get an error when I want to publish config file in console: Class "Spatie\Geocoder\GeocoderServiceProvider" not found...

An idea?

Thank you.

**Comment by freekmurze** [comment]
Hi,

I'm assuming your forgot to install the service provider:

```php
// config/app.php
'providers' => [
    '...',
    'Spatie\Geocoder\GeocoderServiceProvider'
];
```
