### ISSUE TITLE
Language Cannot Be Set to `null` in docs but that's an error?

### ISSUE THREAD

**Issue by lloy0076** [spatie/geocoder#32]
## Version

"spatie/geocoder": "^3.1",

## Bug?

```
C:\laragon\webroots\XXX>php artisan ide-helper:meta

In Geocoder.php line 39:

  Type error: Argument 1 passed to Spatie\Geocoder\Geocoder::setLanguage() must be of the type string, null given, called in C:\laragon\webroots\one-calendar\calendar\vendor\spatie\geocoder\src\GeocoderServiceProvider.php on line 24
```

## Why is it a bug?

Because the documentation says that it could be `null` (see https://github.com/spatie/geocoder/blob/master/README.md).

It is **not** `null` when published - this is a `README.md` thing.

**Comment by freekmurze** [comment]
This should now just work.
