### ISSUE TITLE
Would it make sense to add getAddressForPlaceId()?

### ISSUE THREAD

**Issue by Chris1904** [spatie/geocoder#41]
Hi there,

thanks for this great package. I am not too familiar yet with the Google Maps API, besides the basics.

In my scenario, I use Google's Autocomplete feature in my frontend and it returns me the place object etc. I want to make sure server-side though, that the address provided is within a certain radius.

What are your thoughts on utilizing the place id instead? Would this come with any benefits? I couldn't find much information on Google for it, yet.

Anyways, should be simple enough to add. If it adds any use, I could send a PR.

Thanks!

Chris

**Comment by freekmurze** [comment]
If the code is easy and well tested, I'd accept a PR for this.
