### ISSUE TITLE
Non-compatible with Lumen

### ISSUE THREAD

**Issue by bergstar** [spatie/geocoder#43]
Its imposible to use `vendor:publish` and in the package is self there is a bug with:
`Call to undefined function Spatie\Geocoder\config_path()`

Since only key and language - maybe this package can do with only .env ?..

It works after stripping boot() function and creating config manually 

Good package with clean code - would be nice to use it in lumen without hack.

**Comment by freekmurze** [comment]
We don't use Lumen ourselves, so we aren't going to invest time make this package compatible.
