### ISSUE TITLE
This API project is not authorized to use this API

### ISSUE THREAD

**Issue by pavelph** [spatie/geocoder#51]
That's the error I  get:

Spatie \ Geocoder \ Exceptions \ CouldNotGeocode
Geocoding failed because `This API project is not authorized to use this API.`

I use the same API key as for generating map.

**Comment by freekmurze** [comment]
This error is not caused by this package, but probably because you didn't set up your api project correctly at google. You explicitly have to enable your API project to use geocoding. Research the Google docs for more info or ask for help on a Google oriented public forum.
