### ISSUE TITLE
"Class 'App\Http\Controllers\Geocoder' not found"

### ISSUE THREAD

**Issue by fbc** [spatie/geocoder#53]
I installed the Package and followed the instructions to integrate it into laravel 5.7, but get an error: "Class 'App\Http\Controllers\Geocoder' not found"

What am I doing wrong?

**Comment by danhunsaker** [comment]
You need to either `use Geocoder` for your file, or `\Geocoder` when you access it. PHP namespacing is picky about that.

**Comment by fbc** [comment]
Yup, `use Geocoder;` took care of it.
