### ISSUE TITLE
[Bug|Question] Laravel 6 support?

### ISSUE THREAD

**Issue by ThaDaVos** [spatie/geocoder#74]
Hello,

We noticed, in Laravel 6 the provided Facade isn't working, we get errors about the methods not existing, for example the `setApiKey` method. Maybe something has changed related to Laravel 6 and the facade needs to be updated?

We were able to solve it by adding: `use Spatie\Geocoder\Geocoder`, or better said, including the class directly.

**Comment by freekmurze** [comment]
@rubenvanassche could you add a test that proves the facade is working?

**Comment by rubenvanassche** [comment]
@freekmurze Added test

@ThaDaVos Just installed geocoder in a default laravel 6 application and can use the facade without problems:

```php
        \Geocoder::getCoordinatesForAddress('Infinite Loop 1, Cupertino');
```

Will close this issue for now!

**Comment by freekmurze** [comment]
Thanks @rubenvanassche 👍
