### ISSUE TITLE
Guzzle 7.0 support

### ISSUE THREAD

**Issue by m-bosch** [spatie/geocoder#83]
Because of the release of Guzzle 7.0 the 6.* version is bugfixes only at the moment.
For upgrading see: https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

It would be great if the Geocoder will support the new guzzle so everything is up to date.

**Comment by m-bosch** [comment]
see also  #84

**Comment by freekmurze** [comment]
We'll continue the conversation in #84
