### ISSUE TITLE
Error: Call to undefined method Spatie\Geocoder\Facades\Geocoder::setApiKey()

### ISSUE THREAD

**Issue by gajendra7590** [spatie/geocoder#88]
I am Using Laravel 7.X I have installed properly & also do configure properly as steped given on doc
but getting same error

I Followed Steps From : https://github.com/spatie/geocoder.

Also do config & cache clear, composer dump autoload ...... everything i have done but getting same error please do it why it is going on ...

I have 
**PHP** : 7.4
**Laravel** : 7.X

**Please Review The Loom Video I Recorded** : https://www.loom.com/share/362c98357d2a42499559135b2f5f3b66

**Comment by rodrigopeixotobr** [comment]
Hello, try removing '\Facades', change this:

`Spatie\Geocoder\Facades\Geocoder::setApiKey()`

to something like this:

```
$client = new \GuzzleHttp\Client();
$geocoder = new \Spatie\Geocoder\Geocoder($client);
$geocoder->setApiKey(config('geocoder.key'));
$geocoder->setCountry(config('geocoder.country'));
$result = $geocoder->getCoordinatesForAddress('address');
```

**Comment by monaye** [comment]
I am also having the same `Call to undefined method` for `Geocoder::getCoordinatesForAddress`. Using Laravel 7 as well. 

```
use Spatie\Geocoder\Facades\Geocoder;

~

$geoInfo = Geocoder::getCoordinatesForAddress($shop->address);
```

**Comment by Turpoint** [comment]
> I am also having the same `Call to undefined method` for `Geocoder::getCoordinatesForAddress`. Using Laravel 7 as well.
> 
> ```
> use Spatie\Geocoder\Facades\Geocoder;
> 
> ~
> 
> $geoInfo = Geocoder::getCoordinatesForAddress($shop->address);
> ```

See comment of @rodrigopeixotobr  
Use Spatie\Geocoder\Geocoder instead of Spatie\Geocoder\Facades\Geocoder.
